Repository jetstack/jsctl, pull requests merged in 2022-10, with the labels that each got.

#22 Automatically generate release notes again
  .github/workflows/release.yml
  .goreleaser.yml
Labels: size/XS, lgtm

#25 Fix secrets order
  internal/command/operator.go
  internal/operator/operator.go
  internal/operator/operator_test.go
Labels: size/L

#26 Use GH native changelog API
  .goreleaser.yml
Labels: size/XS, lgtm

#31 Set pull secret for voh when using auto creds
  internal/operator/operator.go
Labels: size/XS, lgtm

#28 Add a test make target
  Makefile
Labels: size/XS, lgtm

#27 Implement a version command
  .goreleaser.yml
  go.mod
  go.sum
  internal/command/command.go
  internal/command/version.go
  main.go
Labels: size/M

#30 Better explain installation errors
  go.mod
  go.sum
  internal/command/operator.go
  internal/operator/crd.go
  internal/operator/operator.go
Labels: lgtm, size/L

#33 Approver policy enterprise secret
  go.mod
  go.sum
  internal/operator/installers/v0.0.1-alpha.13.yaml
  internal/operator/installers/v0.0.1-alpha.16.yaml
  internal/operator/operator.go
  internal/operator/operator_test.go
Labels: size/XXL

#36 Ensure correct number of args are used
  internal/command/auth.go
  internal/command/clusters.go
  internal/command/operator.go
  internal/command/organizations.go
  internal/command/registry.go
  internal/command/users.go
  internal/command/version.go
Labels: lgtm, size/S

#35 Fix panic when missing kubeconfig or cluster
  internal/kubernetes/kubernetes.go
Labels: lgtm, size/S

#38 Prompt user to check supported versions if unknown
  internal/command/operator.go
Labels: size/XS, lgtm

#44 Replace amd64 with x86_64 for uname -m URL generation
  .goreleaser.yml
Labels: size/XS, lgtm

#45 Fix number of args for operator installations apply
  internal/command/operator.go
Labels: size/XS

#56 Correct naming of archives to match uname -m
  .goreleaser.yml
  go.sum
Labels: lgtm, size/L
