Repository jetstack/jsctl, pull requests merged in 2022-09, with the labels that each got.

#2 Import code from private jsctl
  .github/dependabot.yml
  .github/workflows/go.yml
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
  LICENSE
  Makefile
  README.md
  go.mod
  go.sum
  internal/auth/auth.go
  internal/auth/auth_test.go
  internal/client/client.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mocks_test.go
  internal/cluster/templates/agent.yaml
  internal/command/auth.go
  internal/command/clusters.go
  internal/command/command.go
  internal/command/config.go
  internal/command/operator.go
  internal/command/organizations.go
  internal/command/users.go
  internal/config/config.go
  internal/config/config_test.go
  internal/docker/docker.go
  internal/kubernetes/kubernetes.go
  internal/kubernetes/kubernetes_test.go
  internal/kubernetes/testdata/stream.yaml
  internal/operator/installers/v0.0.1-alpha.0.yaml
  internal/operator/installers/v0.0.1-alpha.1.yaml
  internal/operator/installers/v0.0.1-alpha.10.yaml
  internal/operator/installers/v0.0.1-alpha.11.yaml
  internal/operator/installers/v0.0.1-alpha.2.yaml
  internal/operator/installers/v0.0.1-alpha.3.yaml
  internal/operator/installers/v0.0.1-alpha.4.yaml
  internal/operator/installers/v0.0.1-alpha.5.yaml
  internal/operator/installers/v0.0.1-alpha.6.yaml
  internal/operator/installers/v0.0.1-alpha.7.yaml
  internal/operator/installers/v0.0.1-alpha.8.yaml
  internal/operator/installers/v0.0.1-alpha.9.yaml
  internal/operator/operator.go
  internal/operator/operator_test.go
  internal/operator/testdata/key.json
  internal/organization/mocks_test.go
  internal/organization/organization.go
  internal/organization/organization_test.go
  internal/prompt/prompt.go
  internal/prompt/prompt_test.go
  internal/table/table.go
  internal/table/table_test.go
  internal/user/mocks_test.go
  internal/user/user.go
  internal/user/user_test.go
  internal/venafi/venafi.go
  internal/venafi/venafi_test.go
  main.go
Labels: size/XXL, lgtm

#4 Bump goreleaser/goreleaser-action from 2 to 3
  .github/workflows/release.yml
Labels: size/XS, lgtm

#5 Add attribution note
  README.md
Labels: size/S

#7 Release artifact: wrap directory
  .goreleaser.yml
Labels: size/XS

#8 Dashes in asset names, tar archives
  .goreleaser.yml
Labels: size/XS

#6 Fix attributions content & header
  README.md
Labels: lgtm, size/S

#16 Updates readme
  Makefile
  README.md
  docs/reference/README.md
  docs/reference/jsctl_auth.md
  docs/reference/jsctl_auth_login.md
  docs/reference/jsctl_auth_logout.md
  docs/reference/jsctl_clusters.md
  docs/reference/jsctl_clusters_connect.md
  docs/reference/jsctl_clusters_delete.md
  docs/reference/jsctl_clusters_list.md
  docs/reference/jsctl_clusters_view.md
  docs/reference/jsctl_configuration.md
  docs/reference/jsctl_configuration_set.md
  docs/reference/jsctl_configuration_set_organization.md
  docs/reference/jsctl_operator.md
  docs/reference/jsctl_operator_deploy.md
  docs/reference/jsctl_operator_installations.md
  docs/reference/jsctl_operator_installations_apply.md
  docs/reference/jsctl_operator_installations_status.md
  docs/reference/jsctl_operator_versions.md
  docs/reference/jsctl_organizations.md
  docs/reference/jsctl_organizations_list.md
  docs/reference/jsctl_users.md
  docs/reference/jsctl_users_add.md
  docs/reference/jsctl_users_list.md
  docs/reference/jsctl_users_remove.md
  go.mod
  go.sum
  tools/cobra/main.go
  tools/cobra/main_test.go
Labels: size/XXL

#10 Implement automatic registry credential fetching & auth status command
  internal/auth/auth.go
  internal/command/auth.go
  internal/command/command.go
  internal/command/operator.go
  internal/command/registry.go
  internal/operator/operator.go
  internal/operator/operator_test.go
  internal/registry/registry.go
  internal/registry/registry_test.go
  internal/subscription/mocks_test.go
  internal/subscription/subscription.go
  internal/subscription/subscription_test.go
Labels: lgtm, size/XL

#17 Print login URL to terminal
  internal/command/auth.go
Labels: size/XS, lgtm

#20 Downgrade goreleaser
  .github/workflows/release.yml
Labels: size/XS, lgtm

#21 Implement tier selection for operator installations apply
  go.mod
  go.sum
  internal/command/operator.go
  internal/operator/operator.go
  internal/operator/operator_test.go
Labels: size/M
