Repository jetstack/jsctl, pull requests merged in 2023-02, with the labels that each got.

#81 Ensures that manifest generation still works if issuers backup file not provided
  internal/command/operator/apply.go
Labels: size/XS

#82 venafiissuer and venaficlusterissuer were missing an "s"
  internal/cluster/templates/agent.yaml
Labels: size/XS, lgtm

#83 Rename 'v1certmanager' import to 'cmapi'
  internal/kubernetes/clients/clients.go
  internal/kubernetes/clients/issuers.go
  internal/kubernetes/restore/restore.go
  internal/kubernetes/restore/restore_test.go
  internal/kubernetes/status/status.go
  internal/operator/operator.go
  internal/operator/operator_test.go
  internal/venafi/venafi.go
  internal/venafi/venafi_test.go
Labels: lgtm, size/L

#85 Add Fake client for generic Kubernetes client
  internal/kubernetes/clients/clients.go
  internal/kubernetes/clients/fake.go
  internal/kubernetes/clients/generic.go
  internal/kubernetes/clients/installation.go
  internal/kubernetes/clients/issuers.go
Labels: lgtm, size/L

#84 Add x as alias for experimental
  internal/cluster/cluster.go
  internal/command/experimental.go
Labels: size/XS, lgtm

#86 Prevent incorrectly matching images
  internal/kubernetes/status/components/aws_pca_issuer.go
  internal/kubernetes/status/components/cert_discovery_venafi.go
  internal/kubernetes/status/components/cert_manager.go
  internal/kubernetes/status/components/cert_manager_approver_policy.go
  internal/kubernetes/status/components/cert_manager_approver_policy_enterprise.go
  internal/kubernetes/status/components/cert_manager_csi_driver.go
  internal/kubernetes/status/components/cert_manager_csi_driver_spiffe.go
  internal/kubernetes/status/components/cert_manager_istio_csr.go
  internal/kubernetes/status/components/cert_manager_trust_manager.go
  internal/kubernetes/status/components/google_cas_issuer.go
  internal/kubernetes/status/components/isolated_issuer.go
  internal/kubernetes/status/components/jetstack_secure_agent.go
  internal/kubernetes/status/components/jetstack_secure_operator.go
  internal/kubernetes/status/components/kms_issuer.go
  internal/kubernetes/status/components/origin_ca_issuer.go
  internal/kubernetes/status/components/small_step_issuer.go
  internal/kubernetes/status/components/venafi_enhanced_issuer.go
  internal/kubernetes/status/components/venafi_oauth_helper.go
Labels: lgtm, size/L

#87 Add APIPath where missing/ wrong and fix issues in tests
  go.mod
  internal/kubernetes/clients/generic_test.go
  internal/kubernetes/status/status.go
Labels: lgtm, size/S

#88 Latest operator
  go.mod
  go.sum
  internal/command/operator/deploy.go
  internal/kubernetes/apply.go
  internal/kubernetes/scanner.go
  internal/kubernetes/scanner_test.go
  internal/operator/installers/v0.0.1-alpha.17.yaml
  internal/operator/installers/v0.0.1-alpha.20.yaml
  internal/operator/operator.go
  internal/operator/operator_test.go
  internal/registry/credentials.go
Labels: size/XXL, lgtm

#90 Throw error if jsctl was already installed at another location
  install.ps1
  install.sh
Labels: lgtm, size/S
