Repository jetstack/jsctl, pull requests merged in 2023-01, with the labels that each got.

#76 Add script to install the latest version of jsctl
  .goreleaser.yml
  install.ps1
  install.sh
Labels: lgtm, size/L

#77 Fix wrong asset target name in install script
  install.ps1
  install.sh
Labels: lgtm, size/S

#78 Rename login page to TLS Protect
  internal/auth/assets/index.html
  internal/auth/assets/logo.png
Labels: size/XS

#79 Update in-cluster agent configuration
  internal/cluster/templates/agent.yaml
Labels: size/M

#80 Fix typo in error message
  internal/registry/registry.go
Labels: size/XS

#72 Fix group for VEI issuers
  internal/kubernetes/backup/backup.go
  internal/kubernetes/status/status.go
Labels: lgtm, size/S
